package webui

import "strings"

// guidedPageTemplate adds source-console controls to the compact HTML page
// without duplicating the generated template or its layout rules.
func guidedPageTemplate() string {
	page := pageTemplate
	replacements := []struct{ old, new string }{
		{`data-method="deleterelay"><label>Type relay name to confirm <input name="param" value="{{.Slug}}" required>`, `data-method="deleterelay"><label>Type relay name to confirm <input name="param" placeholder="{{.Slug}}" required>`},
		{`data-method="gitstorage"><button>Git storage status</button>`, `data-method="gitstorage"><label>Repository owner <input name="param" required pattern="[0-9a-fA-F]{64}" placeholder="64 hex pubkey"></label><label>Repository identifier <input name="param" required maxlength="256" placeholder="repository name"></label><button>Git storage status</button>`},
		{`data-method="setmember"><label>Pubkey <input name="param" pattern="[0-9a-f]{64}" required></label><label>JSON patch <input name="param" value="{}"></label><button>Save member</button>`, `data-method="setmember" data-compose="member"><label>Pubkey <input name="member-pubkey" pattern="[0-9a-f]{64}" required></label><label>Name <input name="member-name"></label><label>Note <input name="member-note"></label><label>Role <select name="member-role"><option value="member">Member</option><option value="moderator">Moderator</option></select></label><button>Save member</button>`},
		{`data-method="setpolicy"><label>JSON policy patch <textarea name="param">{}</textarea></label><button>Apply policy</button>`, `data-method="setpolicy" data-compose="memberInvites"><label>Member invite depth <input name="member-invite-depth" type="number" min="0" max="100" value="0"></label><label>Live invites per member <input name="member-invite-quota" type="number" min="0" max="1000" value="0"></label><button>Save member invites</button></form><form class="rpc" on-submit="this.querySelector('button').disabled=true" data-method="setpolicy"><label>JSON policy patch <textarea name="param">{}</textarea></label><button>Apply policy</button>`},
		{`data-method="changerelaydescription"><label>Description <textarea name="param">{{.Policy.Description}}</textarea></label><button>Save description</button>`, `data-method="changerelaydescription"><label>Description <textarea name="param">{{.Policy.Description}}</textarea></label><button>Save description</button></form><form class="rpc" on-submit="this.querySelector('button').disabled=true" data-method="changerelayicon"><label>Icon URL <input name="param" type="url" maxlength="2000" value="{{.Policy.Icon}}" placeholder="https://…/icon.png"></label><button>Save icon</button>`},
		{`data-method="transferowner"><label>New owner pubkey <input name="param" required></label><button>Transfer ownership</button>`, `data-method="transferowner"><label>New owner pubkey <input name="param" required></label><button>Transfer ownership</button></form><form class="rpc" on-submit="this.querySelector('button').disabled=true" data-method="setpolicy" data-compose="identity"><label>Contact <input name="identity-contact" value="{{.Policy.Contact}}" type="email" placeholder="you@example.com"></label><label>Banner URL <input name="identity-banner" value="{{.Policy.Banner}}" type="url" placeholder="https://…/banner.png"></label><label>Posting policy URL <input name="identity-posting" value="{{.Policy.PostingPolicy}}" type="url" placeholder="https://…/posting"></label><label>Privacy policy URL <input name="identity-privacy" value="{{.Policy.PrivacyPolicy}}" type="url" placeholder="https://…/privacy"></label><label>Tags <input name="identity-tags" value="{{join .Policy.Tags ", "}}" placeholder="bitcoin, cats"></label><label>Languages <input name="identity-languages" value="{{join .Policy.LanguageTags ", "}}" placeholder="en, pt-BR"></label><label>Countries <input name="identity-countries" value="{{join .Policy.RelayCountries ", "}}" placeholder="US, DE"></label><button>Save directory identity</button>`},
		{`data-method="disallowkind"><label>Kind <input name="param" type="number" required></label><button>Block kind</button></form>`, `data-method="disallowkind"><label>Kind <input name="param" type="number" required></label><button>Block kind</button></form><form class="rpc" on-submit="this.querySelector('button').disabled=true" data-method="setretention"><label>Kind or null <input name="param" value="null" required></label><label>Keep days <input name="param" type="number" min="0" required></label><button>Save retention</button>`},
		{`data-method="deleterelay"><label>Type relay name to confirm`, `data-method="setsuccession" data-compose="succession"><label>Heir pubkey <input name="succession-heir" pattern="[0-9a-f]{64}" required></label><label>Hand over after days <select name="succession-days"><option value="90">90</option><option value="180" selected>180</option><option value="365">365</option></select></label><button>Set heir</button></form><form class="rpc" on-submit="this.querySelector('button').disabled=true" data-method="clearsuccession"><button>Clear heir</button></form><form class="rpc" on-submit="this.querySelector('button').disabled=true" data-method="deleterelay"><label>Type relay name to confirm`},
	}
	for _, replacement := range replacements {
		page = strings.Replace(page, replacement.old, replacement.new, 1)
	}
	old := `let params=[...form.querySelectorAll("[name=param]")].map(x=>{try{return JSON.parse(x.value)}catch{return x.value}});if(form.dataset.jsonParams&&params.length===1&&Array.isArray(params[0]))params=params[0];`
	newCode := `let params=[...form.querySelectorAll("[name=param]")].map(x=>{try{return JSON.parse(x.value)}catch{return x.value}});if(form.dataset.compose==="member")params=[form.elements["member-pubkey"].value,{name:form.elements["member-name"].value,note:form.elements["member-note"].value,role:form.elements["member-role"].value}];if(form.dataset.compose==="memberInvites")params=[{memberInvites:{depth:Number(form.elements["member-invite-depth"].value),quota:Number(form.elements["member-invite-quota"].value)}}];if(form.dataset.compose==="succession")params=[{heir:form.elements["succession-heir"].value,afterDays:Number(form.elements["succession-days"].value)}];if(form.dataset.compose==="identity")params=[{contact:form.elements["identity-contact"].value,banner:form.elements["identity-banner"].value,postingPolicy:form.elements["identity-posting"].value,privacyPolicy:form.elements["identity-privacy"].value,tags:form.elements["identity-tags"].value.split(",").map(x=>x.trim()).filter(Boolean),languageTags:form.elements["identity-languages"].value.split(",").map(x=>x.trim()).filter(Boolean),relayCountries:form.elements["identity-countries"].value.split(",").map(x=>x.trim()).filter(Boolean)}];if(form.dataset.jsonParams&&params.length===1&&Array.isArray(params[0]))params=params[0];`
	return strings.Replace(page, old, newCode, 1)
}
